### ISSUE TITLE
Your codecov badge

### ISSUE THREAD

**Issue by jchodera** [MolSSI-SSS/QM_2017_SSS_Team4#2]
[![codecov](https://codecov.io/gh/MolSSI-SSS/QM_2017_SSS_Team4/branch/master/graph/badge.svg)](https://codecov.io/gh/MolSSI-SSS/QM_2017_SSS_Team4)

**Comment by jchodera** [comment]
Here's the source for the badge:
```
[![codecov](https://codecov.io/gh/MolSSI-SSS/QM_2017_SSS_Team4/branch/master/graph/badge.svg)](https://codecov.io/gh/MolSSI-SSS/QM_2017_SSS_Team4)
```

**Comment by vidsharma** [comment]
Okay, thanks! We got it.
